Create bind for RecyclerView-FastScroll
xamarin/XamarinComponents pull request #1186
Opened 2021-05-26 09:21 UTC by 4brunu

2021-05-27 10:28 UTC, moljac requested changes
please could you rename folder from `RecyclerView-FastScroll` to `RecyclerView.FastScroll` to keep it somehow consistent with .NET naming.

2021-05-27 10:51 UTC, 4brunu commented
Done, I also updated the monoandroid to version 11.0, but now the build is failing

2021-05-27 10:53 UTC, moljac commented
> Done, I also updated the monoandroid to version 11.0, but now the build is failing

please revert to 9.0

and build is failing because of changes for .NET 6. We are working on that issue

2021-05-27 10:54 UTC, 4brunu commented
Done 👍

2021-05-27 14:35 UTC, moljac commented
/azp run

2021-05-27 15:11 UTC, moljac commented
@4brunu

Error:

```
Script Arguments:
  Root directory: /Users/runner/work/1/s
  Root output directory: output
  Valid package namespaces: Xamarin, Mono, SkiaSharp, HarfBuzzSharp, mdoc, Masonry, GoogleGson, AndroidEasingFunctions, Square, JakeWharton.Picasso2OkHttp3Downloader, RecyclerViewAnimators, GoogleGson

Found 1 NuGet packages to validate.
Verifying NuGet metadata of /Users/runner/work/1/s/output/RecyclerView.FastScroll.2.0.1.nupkg...
NuGet metadata validation failed for /Users/runner/work/1/s/output/RecyclerView.FastScroll.2.0.1.nupkg:
The package does not start with any of the following namespaces: [ 'Xamarin', 'Mono', 'SkiaSharp', 'HarfBuzzSharp', 'mdoc', 'Masonry', 'GoogleGson', 'AndroidEasingFunctions', 'Square', 'JakeWharton.Picasso2OkHttp3Downloader', 'RecyclerViewAnimators', 'GoogleGson' ]
```

please add Xamarin as nuget package prefix.

I tend to make everything with prefix (nuget packageid, namespaces and assemblyname)

2021-05-27 15:15 UTC, 4brunu commented
@moljac Can you please confirm if https://github.com/xamarin/XamarinComponents/pull/1186/commits/eedefc63df40e00232a212d9556e47732ad486b7 does what you asked for?

2021-05-27 15:36 UTC, moljac requested changes
Xamarin prefix

2021-05-27 15:36 UTC, moljac commented on Android/RecyclerView.FastScroll/source/RecyclerView.FastScroll/RecyclerView.FastScroll.csproj
> +    <PackageId>RecyclerView.FastScroll</PackageId>
This is nuget ID (needs Xamarin prefix)

2021-05-27 15:43 UTC, 4brunu commented on Android/RecyclerView.FastScroll/source/RecyclerView.FastScroll/RecyclerView.FastScroll.csproj
> +    <PackageId>RecyclerView.FastScroll</PackageId>
Done, thanks 👍

2021-05-28 16:05 UTC, moljac approved these changes
LGTM

2021-05-28 16:06 UTC, merged