Added the binding for TwitterImagePipeline v2.2.2
xamarin/XamarinComponents pull request #127
Opened 2017-03-09 23:07 UTC by mattleibow

- still need to create component images

2017-03-09 23:16 UTC, mattleibow commented
I am having issues binding this one:

```csharp
// @protocol TIPLogger <NSObject>
[Protocol, Model]
[BaseType(typeof(NSObject), Name = "TIPLogger")]
interface TIPLogger
{
	// @required -(void)tip_logWithLevel:(TIPLogLevel)level file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(int)line format:(NSString * _Nonnull)format, ... __attribute__((format(NSString, 5, 6)));
	// TODO: [Internal]
	[Abstract]
	[Export("tip_logWithLevel:file:function:line:format:", IsVariadic = true)]
	void Log(TIPLogLevel level, string file, string function, int line, string format, IntPtr varArgs);

	// @optional -(BOOL)tip_canLogWithLevel:(TIPLogLevel)level;
	[Export("tip_canLogWithLevel:")]
	bool CanLog(TIPLogLevel level);
}
```

```obj-c
@protocol TIPLogger <NSObject>

@required
- (void)tip_logWithLevel:(TIPLogLevel)level file:(nonnull NSString *)file function:(nonnull NSString *)function line:(int)line format:(nonnull NSString *)format, ... NS_FORMAT_FUNCTION(5,6);

@optional
- (BOOL)tip_canLogWithLevel:(TIPLogLevel)level;

@end
```

According to the docs: https://developer.xamarin.com/guides/cross-platform/macios/binding/objective-c-libraries/#Binding_Objective-C_Argument_Lists I can do stuff, but in this case it is a protocol that the USER must implement.

Any suggestions?

2017-03-10 02:22 UTC, migueldeicaza commented
Your best in this scenario is to change the code in the Objective-C library to avoid calling the Log method with the variadic arguments and change the contract.   This effectively means we would need a fork of the library.

2017-03-10 03:47 UTC, mattleibow commented
Thanks for confirming that this cannot be bound. I don't think we want to maintain a fork just yet, so we meet in the middle - I insert an extra file in the xcode project. And then we use that bindable type instead.

2017-08-11 21:14 UTC, bholmes requested changes
I have listed some comments for you to consider changing.  Also review all of your TODOs to ensure that you have not forgotten anything.

2017-08-11 21:14 UTC, bholmes commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +		TIPImageFetchDownloadProvider ImageFetchDownloadProvider { get; set; }
Not using the interface version of Protocols where possible.  See my diff for more instances.

https://gist.github.com/bholmes/12abcb7d4628f90e95dcc6b99beea834

2017-08-11 21:14 UTC, bholmes commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +		void ImageFetchDownloadDidStart(ITIPImageFetchDownload download);
Consider dropping all of the ImageFetchDownload prefixes in the methods.

2017-08-11 21:14 UTC, bholmes commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +		void ImageFetchOperationDidStart(TIPImageFetchOperation op);
Consider dropping all of the ImageFetchOperation prefixes on all methods.

2017-08-11 21:14 UTC, bholmes commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +	[BaseType(typeof(NSObject), Name = "TI
Consider removing all of the FetchHelper prefixes on all method names.

2017-08-11 21:14 UTC, bholmes commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +		// TODO: this is really a short
Did you want to change this?  Can it be a short?  There are 3 instances of this in this class.

2017-08-11 21:14 UTC, bholmes commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +		//[RequiresSuper] // TODO
I am not 100% sure what to do here.  I am only getting one Google hit for this Attribute.  It looks like you should add an Advice attribute telling the user to call the base class?

https://bugzilla.xamarin.com/show_bug.cgi?id=58350

`[Advice ("You must call the base method when overriding.")]`

2017-08-11 21:14 UTC, bholmes commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/Additions.cs
> +		public NSDictionary<NSString, TIPImageFetchProgressiveLoadingPolicy> ProgressiveLoadingPolicies { get; set; }
Should be `ITIPImageFetchProgressiveLoadingPolicy `

2017-08-11 21:14 UTC, bholmes commented on manifest.yaml
> +  MacBuildTargets: [ component, samples ]
should be [ samples, component ]  

inconsistent order.

2017-08-17 12:24 UTC, mattleibow commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +		// TODO: this is really a short
Currently, this is not yet supported by the binding engine: https://bugzilla.xamarin.com/show_bug.cgi?id=58845

But, I did it manually.

2017-08-17 12:24 UTC, mattleibow commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +		TIPImageFetchDownloadProvider ImageFetchDownloadProvider { get; set; }
Updated my code.

2017-08-17 12:27 UTC, mattleibow commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +		//[RequiresSuper] // TODO
Done.

2017-08-17 12:27 UTC, mattleibow commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +		void ImageFetchOperationDidStart(TIPImageFetchOperation op);
done.

2017-08-17 12:27 UTC, mattleibow commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +		void ImageFetchDownloadDidStart(ITIPImageFetchDownload download);
done.

2017-08-17 12:31 UTC, mattleibow commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs
> +	[BaseType(typeof(NSObject), Name = "TI
done.

2017-08-17 12:31 UTC, mattleibow commented on iOS/TwitterImagePipeline/source/TwitterImagePipeline/Additions.cs
> +		public NSDictionary<NSString, TIPImageFetchProgressiveLoadingPolicy> ProgressiveLoadingPolicies { get; set; }
changed

2017-08-17 12:35 UTC, mattleibow commented on manifest.yaml
> +  MacBuildTargets: [ component, samples ]
changed

2017-08-17 16:56 UTC, bholmes approved these changes

2017-08-17 16:56 UTC, merged