[mapbox] iOS: update to SDK v3.5.0
xamarin/XamarinComponents pull request #140
Opened 2017-03-30 17:09 UTC by davideme

### :pushpin: References
* **iOS Release:**  https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.5.0

### :tophat: What is the goal?

Provide an update version of mapbox sdk, from 3.3.7 to 3.5.0 .
This also adds new bindings corresponding to new methods and set as obsolete method deprecated on the iOS SDK.

### How is it being implemented?

- Use Objective Sharpie to generate ApiDefinition.cs and StructsAndEnums.cs.
- Reorganize the code to current order of ApiDefinition
- Review documentation and naming
- Review the [Binding Types Reference Guide](https://developer.xamarin.com/guides/cross-platform/macios/binding/binding-types-reference/)

### Pending Questions
- In AnnotationView how should we bind WeakDelegate and Delegate?
- Should the unsafe notation be in the ApiDefinition?
- Should CLLocationCoordinate2D be referenced as IntPtr and be used via a wrapper method in the Additions.cs?

2017-03-30 17:09 UTC, dnfclas commented
@__davideme__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla2.dotnetfoundation.org.

It will cover your contributions to all .NET Foundation-managed open source projects.
_Thanks,
.NET Foundation Pull Request Bot_

2017-03-30 17:19 UTC, dnfclas commented
__@davideme__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, .NET Foundation Pull Request Bot_

2017-04-03 16:01 UTC, Redth commented
The approach I've used in the past to update Mapbox iOS bindings is to download the mapbox sdk version for the current bindings, and then the new version we want to bind to, and run a diff on the header files between those versions.  This should net you the changes required for the binding.

2017-04-07 01:13 UTC, SotoiGhost commented
@davideme 

I'll review the PR to see if I can make some suggestions, but for now, I'll try to answer the pending questions:

> * In AnnotationView how should we bind WeakDelegate and Delegate?

I reviewed **AnnotationView** class and .h file in Xcode and couldn't find any delegate property. Maybe you mean **MapView** or **OfflineStorage** classes?

Anyways, the preferred way to bind Protocols is as described in [Binding Objective-C Libraries][1] in **New in MonoTouch 7.0** section. For example:

```csharp
interface IFooDelegate
{
}

[Protocol, Model]
[BaseType (typeof (NSObject))]
interface FooDelegate
{
    // Foo Protocols methods
}

[BaseType (typeof (FooType))]
interface Foo
{
    [NullAllowed, Export ("delegate")]
    IFooDelegate Delegate { get; set; }
}
```

[1]: https://developer.xamarin.com/guides/cross-platform/macios/binding/objective-c-libraries/#Binding_Protocols

---

> * Should the unsafe notation be in the ApiDefinition?

No, you can use it when you are wrapping something in Additions/Extensions class but it's not recommended to use it in ApiDefinition.

---

> * Should CLLocationCoordinate2D be referenced as IntPtr and be used via a wrapper method in the Additions.cs?

Yes, you can change the reference to IntPtr and use the wrapper but I think that you need to include the `WithCoordinates` method inside the `fixed` code block to avoid strange behaviours in ObjC side. You could do:

```csharp
public static Polygon WithCoordinates (CLLocationCoordinate2D[] coords, nuint count)
{
    Polygon polygon;
    fixed (CLLocationCoordinate2D* ptr = &coordinates[0]) {
        polygon = WithCoordinates(ptr, count);
    }
    
    return polygon;
}
```

---

> * StyleValue and subclasses are represented as ObjC generic how should I translate that in the Binding?

For this point, I'll quote Doug that talks about generics in this [WWDC][2] video at minute 27:23:

> So the entire lightweight generics feature is based on a type erasure model. Which means that the compiler has all of this rich static type information but it erases that information when generating code.

IOW, generics classes end like any other class without generic in the binary file. So, you can leave it like it is and document that those parameters/return methods could be **Foo**, **Goo**, **Hoo** classes.

[2]: https://developer.apple.com/videos/play/wwdc2015/401/

2017-04-07 17:04 UTC, dalexsoto commented
Just an additional comment on generics in this case

Unfortunatelly this API takes several NSObject derived types that do not have a parent/child relationship so being NSObject its only relation it really doesn't help at all having a generic type and would only complicate the binding a lot. Even in ObjC I do not see the benefit at all.

That being said you can use the [AdviceAttribute](https://developer.xamarin.com/guides/cross-platform/macios/binding/binding-types-reference/#AdviceAttribute) to document the types that you can use/cast to here. This attribute info will be shown inside the IDE in the completion box in a future release of VS.

2017-04-12 21:41 UTC, SotoiGhost reviewed
@davideme many of this reviews are suggestions and other ones you need to add or change the code.

If you have any doubt, let me know.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +	 Delegates = new string[] { "WeakDelegate" })]
I think here's missing the Events argument if you want to add events to class. Add `Events = new Type [] { typeof (MapViewDelegate) }`, otherwise, remove the Delegates argument. It doesn't do anything without Events argument.

Also, if you desire is to add events, you can add some optionals attributes listed in [Model Definitions][1] doc to protocol methods to specify the naming of the event or the event args. Please, try giving event names following the .NET conventions, you can give you an idea following this [doc][2].

[1]: https://developer.xamarin.com/guides/cross-platform/macios/binding/binding-types-reference/#Model_Definitions
[2]: https://msdn.microsoft.com/en-us/library/h0eyck3s(v=vs.71).aspx

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe void SetVisibleCoordinates (CLLocationCoordinate2D coordinates, nuint count, UIEdgeInsets insets, bool animated);
Use the wrapper as before.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe void SetVisibleCoordinates (CLLocationCoordinate2D coordinates, nuint count, UIEdgeInsets insets, double direction, double duration, [NullAllowed] CAMediaTimingFunction function, [Null
Use the wrapper as before.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        CoordinateBounds ConvertRect (CGRect rect, [NullAllowed] UIView view);
Change the name as before (`ConvertRectToCoordinateBounds`) to avoid breaking changes.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        CGRect ConvertCoordinateBounds (CoordinateBounds bounds, [NullAllowed] UIView view);
Change the name as before (`ConvertCoordinateBoundsToRect`) to avoid breaking changes.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        AnnotationView DequeueReusableAnnotation (string identifier);
Change the name as before (`DequeueReusableAnnotationView`) to avoid breaking changes.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        IAnnotation[] VisibleAnnotationsInRect (CGRect rect);
A better name for this method could be `GetVisibleAnnotations`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        Feature[] GetVisibleFeaturesAtPoint (CGPoint point, [NullAllowed] NSSet<NSString> styleLayerIdentifiers);
Change `styleLayerIdentifiers` param to `string []` to avoid breaking changes.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        Feature[] GetVisibleFeaturesAtPoint (CGPoint point, [NullAllowed] NSSet<NSString> styleLayerIdentifiers, [NullAllowed] NSPredicate predicate);
You can change `styleLayerIdentifiers` param to `string []` to help developers to pass that instead of creating an `NSSet` from strings array and pass it.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        Feature[] GetVisibleFeaturesInRect (CGRect rect, [NullAllowed] NSSet<NSString> styleLayerIdentifiers);
Change the `styleLayerIdentifiers` param to `string []` to avoid breaking changes.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        Feature[] GetVisibleFeaturesInRect (CGRect rect, [NullAllowed] NSSet<NSString> styleLayerIdentifiers, [NullAllowed] NSPredicate predicate);
You can change `styleLayerIdentifiers` param to `string []` to help developers to pass that instead of creating an `NSSet` from strings array and pass it.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +		[Export ("mapView:annotationCanShowCallout:"), DelegateName("CanShowCallout"), DefaultValue(null)]
The documentation of this method in **MGLMapViewDelegate.h** file state that:

> If the return value is `NO`, or if this method is absent from the delegate, or
 if the annotation lacks a title, the annotation will not show a callout even
 when selected.

So, I think the Default Value must be `false` or use [NoDefaultValue] attribute instead.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        Shape ShapeWithData (NSData data, NSStringEncoding encoding, [NullAllowed] out NSError outError);
A better name for this method could be `From`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        //string Subtitle { get; set; }
Is there any reason of why `Title` and `Subtitle` are commented?

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        NSData GeoJSONDataUsingEncoding (NSStringEncoding encoding);
A better name for this method could be `GetGeoJsonData`. We avoid using more than 3 capital letters in a row.

Also, if the first param describes the end of the method name, we usually remove it. We use params to help to create shorter method names. This frequently happens when the method ends with `Using*`, `For*` or `With*`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    [BaseType (typeof(NSLengthFormatter))]
`Name = "MGLDistanceFormatter"` is missing here.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        string StringFromDistance (double distance);
A better name for this method could be `GetStringFromDistance`, `GetString` or `DistanceToString`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe CLLocationCoordinate2D Coordinates { get; }
This is an array of `CLLocationCoordinate2D`, a wrapper will be needed.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe void GetCoordinates (CLLocationCoordinate2D coords, NSRange range);
This is an array of `CLLocationCoordinate2D`, a wrapper will be needed.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe void SetCoordinates (CLLocationCoordinate2D coords, nuint count);
This is an array of `CLLocationCoordinate2D`, a wrapper will be needed. The wrapper could have just an array of `CLLocationCoordinate2D` as param and, internally, pass the length of the array to this method.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe void InsertCoordinates (CLLocationCoordinate2D coords, nuint count, nuint index);
This is an array of `CLLocationCoordinate2D`, a wrapper will be needed. The wrapper could have an array of `CLLocationCoordinate2D` as param and, internally, pass the length of the array to this method.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe void AppendCoordinates (CLLocationCoordinate2D coords, nuint count);
This is an array of `CLLocationCoordinate2D`, a wrapper will be needed. The wrapper could have just an array of `CLLocationCoordinate2D` as param and, internally, pass the length of the array to this method.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe void ReplaceCoordinatesInRange (NSRange range, CLLocationCoordinate2D coords);
This is an array of `CLLocationCoordinate2D`, a wrapper will be needed.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe void ReplaceCoordinatesInRange (NSRange range, CLLocationCoordinate2D coords, nuint count);
This is an array of `CLLocationCoordinate2D`, a wrapper will be needed.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        IntPtr Zero { get; }
You can create a wrapper to return the value as a struct instead of a pointer. You can use [this code][1] as an example.

[1]: https://github.com/SotoiGhost/GoogleApisForiOSComponents/blob/master/Google.Maps/source/Google.Maps/Extensions.cs#L18-L31

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        //CLLocationCoordinate2D Coordinate { get; set; }
Is there any reason to comment `Coordinate` property?

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe Polygon WithCoordinates (CLLocationCoordinate2D coords, nuint count);
Change the method as it was before and use the wrapper.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe Polygon WithCoordinates (CLLocationCoordinate2D coords, nuint count, [NullAllowed] Polygon[] interiorPolygons);
Change the method as it was before and use the wrapper.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe Polyline WithCoordinates (CLLocationCoordinate2D coords, nuint count);
Change the method as it was before and use the wrapper.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        //string Subtitle { get; set; }
Is there any reason to comment `Title` and `Subtitle` properties?

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        bool IsEqualToMapCamera (MapCamera otherCamera);
A better name for this method could be `Equals`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        Source SourceWithIdentifier (string identifier);
A better name for this method could be `GetSource`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        StyleLayer LayerWithIdentifier (string identifier);
A better name for this method could be `GetLayer`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        UIImage ImageForName (string name);
A better name for this method could be `GetImage`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        void RemoveImageForName (string name);
A better name for this method could be `RemoveImage`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        void PresentCallout (CGRect rect, UIView view, UIView constrainedView, bool animated);
Change params name as it was before for a better understanding of the method.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        bool AnchoredToAnnotation { [Bind ("isAnchoredToAnnotation")] get; }
A better name for this method could be `IsAnchoredToAnnotation`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    [BaseType(typeof(Shape), Name = "MGLShape")]
The value in `Name` param is wrong, it should be `MGLPointCollection`.

Also, add `[DisableDefaultCtor]` due there is no other way to set `Coordinates` but through the static method.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe PointCollection PointCollectionWithCoordinates (CLLocationCoordinate2D coords, nuint count);
This is an array of `CLLocationCoordinate2D`, a wrapper will be needed. You can create a wrapper that just receives an array of `CLLocationCoordinate2D` and pass the count internally to this method.

Also, a better name for this method could be `From`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe CLLocationCoordinate2D Coordinates { get; }
This is an array of CLLocationCoordinate2D, a wrapper will be needed.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        unsafe void GetCoordinates (CLLocationCoordinate2D coords, NSRange range);
This is an array of CLLocationCoordinate2D, a wrapper will be needed.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    interface ShapeCollection
Add [DisableDefaultCtor] due there is no other way to set `Shapes` but through the static method.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        ShapeCollection WithShapes (Shape[] shapes);
A better name for this method could be `From`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        void SetMaximumAllowedMapboxTiles (ulong maximumCount);
Change the name as it was before (`SetMaxAllowedMapboxTiles`) to avoid breaking changes.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        bool GetObjectValue ([NullAllowed] out NSObject obj, string @string, [NullAllowed] out string error);
Change the param name from `@string` to `str` or `aString`, and change the last type to `NSString` to avoid breaking changes.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        bool GetObjectValue ([NullAllowed] out NSObject obj, string @string, [NullAllowed] out string error);
Change the param name from `@string` to `str` or `aString`, and change the last type to `NSString` to avoid breaking changes.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    [BaseType (typeof(NSFormatter))]
`Name = "MGLCoordinateFormatter"` is missing here.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        bool GetObjectValue ([NullAllowed] out NSObject obj, string @string, [NullAllowed] out string error);
Change the param name from `@string` to `str` or `aString`, and change the last type to `NSString` to avoid breaking changes.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        NSDictionary<NSString, NSObject> GeoJSONDictionary { get; }
A better name for this property could be `GeoJsonDictionary`

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    [BaseType(typeof(ShapeCollection), Name = "MGLShapeCollectionFeature")]
Add `[DisableDefaultCtor]` due there is no other way to set `Shapes` property but from static methods.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +		ShapeCollectionFeature ShapeWithData(NSData data, NSStringEncoding encoding, [NullAllowed] out NSError outError);
A better name for this method could be `From`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    [BaseType (typeof(NSObject))]
`Name = "MGLOfflineStorageDelegate"` is missing here.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        NSUrl URLForResourceOfKind (OfflineStorage storage, ResourceKind kind, NSUrl url);
Change the `URL` to `Url` in the method name. Also, a better name for this method could be `UrlForResoure`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    [BaseType (typeof(NSObject))]
`Name = "MGLStyleLayer"` is missing here.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        bool Visible { [Bind ("isVisible")] get; set; }
A better name for this property could be `IsVisible`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        NSString DefaultValue { get; }
You can add these two Fields inside of StyleValue class.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        NSValue ValueWithMGLTransition (Transition transition);
A better name for this method could be `GetValue`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        Transition MGLTransitionValue { get; }
A better name for this property could be `TransitionValue `.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    interface StyleValue : INSObjectProtocol
Better names for these static methods could be `GetValue`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        ConstantStyleValue ValueWithRawValue (NSObject rawValue);
A better name for this method could be `GetValue`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        StyleFunction FunctionWithStops (NSDictionary<NSNumber, StyleValue> stops);
A better name for this method could be `From`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        StyleFunction FunctionWithInterpolationBase (nfloat interpolationBase, NSDictionary<NSNumber, StyleValue> stops);
A better name for this method could be `From`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        CameraStyleFunction FunctionWithInterpolationMode (InterpolationMode interpolationMode, NSDictionary<NSObject, StyleValue> stops, [NullAllowed] NSDictionary<NSString, NSObject> options);
A better name for this method could be `From`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        SourceStyleFunction FunctionWithInterpolationMode (InterpolationMode interpolationMode, [NullAllowed] NSDictionary<NSObject, StyleValue> stops, string attributeName, [NullAllowed] NSDictionar
A better name for this method could be `From`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        CompositeStyleFunction FunctionWithInterpolationMode (InterpolationMode interpolationMode, NSDictionary<NSObject, NSDictionary<NSObject, StyleValue>> stops, string attributeName, [NullAllowed
A better name for this method could be `From`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    interface NSValue_MGLLineStyleLayerAdditions
These five methods cannot be bound, due there are no static methods in categories and we do not have access to `NSValue` class to add these methods. There is a workaround (a very ugly one) and I do not recommend to use it.

@bholmes, @Redth what do you think?

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    interface NSValue_MGLFillStyleLayerAdditions
These two methods cannot be bound, due there are no static methods in categories and we do not have access to `NSValue` class to add these methods. There is a workaround (a very ugly one) and I do not recommend to use it.

@bholmes, @Redth what do you think?

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    interface NSValue_MGLSymbolStyleLayerAdditions
These 20 methods cannot be bound, due there are no static methods in categories and we do not have access to `NSValue` class to add these methods. There is a workaround (a very ugly one) and I do not recommend to use it.

@bholmes, @Redth what do you think? I think there are too many static methods to be ignored.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    interface NSValue_MGLCircleStyleLayerAdditions
These two methods cannot be bound, due there are no static methods in categories and we do not have access to `NSValue` class to add these methods. There is a workaround (a very ugly one) and I do not recommend to use it.

@bholmes, @Redth what do you think?

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    [BaseType (typeof(NSObject))]
`Name = "MGLSource"` is missing here.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        IFeature[] FeaturesInSourceLayersWithIdentifiers (NSSet<NSString> sourceLayerIdentifiers, [NullAllowed] NSPredicate predicate);
A better name for this method could be `GetFeatures`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    partial interface MGLShapeSourceOptionConstants
A better name for this could be `ShapeSourceOptionConstants`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        NSUrl URL { get; set; }
A better name for this property is `Url`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        IFeature[] FeaturesMatchingPredicate ([NullAllowed] NSPredicate predicate);
A better name for this method `GetFeatures`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +    [BaseType (typeof(NSObject))]
`Name = "MGLAttributionInfo"` is missing here.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        NSUrl URL { get; set; }
A better name for this method could be `Url`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        bool FeedbackLink { [Bind ("isFeedbackLink")] get; set; }
A better name for this method could be `IsFeedbackLink`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        NSUrl FeedbackURLAtCenterCoordinate (CLLocationCoordinate2D centerCoordinate, double zoomLevel);
A better name for this method could be `GetFeedbackUrl`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/StructsAndEnums.cs
> +	public struct Transition
Is better that fields start with capital letter.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/StructsAndEnums.cs
> +		SpriteJSON
A better name for this is `SpriteJson`.

2017-04-12 21:41 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/StructsAndEnums.cs
> +	public struct StyleLayerDrawingContext
Is better that fields start with capital letter.

2017-04-21 18:23 UTC, davideme commented
@SotoiGhost Most of the changes requested have done.
It remains All the extensions that cannot be bound, we should decide what to do.

In the meanwhile, I'm working on the wrapper for all the IntPtr that don't have yet a wrapper. And I also added some missing Obsolete annotations.

2017-05-03 10:41 UTC, davideme commented
@SotoiGhost Why not mapping all these categories static method to another class in C#?
NSValue_MGLLineStyleLayerAdditions become LineStyleLayerAdditionsExt, that contains all the static methods on NSValue ?

2017-05-03 13:25 UTC, davideme commented
I applied the changes in my last commit and used them in my project. You need to used the *Ext class for static method, but it seems good enough for me.

2017-05-09 01:50 UTC, SotoiGhost reviewed
@davideme 

I added some comments related with wrappers, everything else seems ok but for **FooExt** classes.

Leaving `FooExt` classes as they are, will generate missing symbols at compile time. At the moment that you add `[BaseType]` to an interface, the binding generator will create a class that points to `FooExt` symbol inside Mapbox library, so, when you try to compile, the compiler will complain that `FooExt` symbol doesn't exist.

The only way that I can think to bind these methods is creating static classes that call static methods of categories. It's an ugly workaround, but I think is the only way that it can be bound:

https://gist.github.com/SotoiGhost/e39b989eaefdc41cdebaf064951117d3

If you want to apply that or comment all static methods in categories.

2017-05-09 01:50 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        void SetCoordinates (IntPtr coords, nuint count);
I think the wrapper for this method is missing.

2017-05-09 01:50 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        void InsertCoordinates (IntPtr coords, nuint count, nuint index);
I think the wrapper for this method is missing.

2017-05-09 01:50 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        void AppendCoordinates (IntPtr coords, nuint count);
I think the wrapper for this method is missing.

2017-05-09 01:50 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        void ReplaceCoordinatesInRange (NSRange range, IntPtr coords);
I think the wrapper for this method is missing.

2017-05-09 01:50 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        void ReplaceCoordinatesInRange (NSRange range, IntPtr coords, nuint count);
I think the wrapper for this method is missing.

2017-05-09 01:50 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        PointCollection From (IntPtr coords, nuint count);
I think the wrapper for this method is missing.

2017-05-09 01:50 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        IntPtr Coordinates { get; }
I think the wrapper for this method is missing.

2017-05-09 01:50 UTC, SotoiGhost commented on XPlat/Mapbox/iOS/source/MapboxSDK.iOS/ApiDefinition.cs
> +        void GetCoordinates (IntPtr coords, NSRange range);
I think the wrapper for this method is missing.

2017-05-16 01:12 UTC, SotoiGhost requested changes
@davideme 

I saw that you uploaded the Mapbox framework. This is something that we don't allow in our repositories for the following reasons:

1. To reduce the size of our repositories: avoiding uploading binaries, it prevents the size from increasing to GB.
2. Due to licensing: Some enterprises have licenses that strictly prohibit the redistribution of its binaries other than its own official page. Adding it to a public repository it's taken as redistribution.

To avoid these statements, we use makefiles and cakefiles to download binaries.

You will need to remove the Mapbox framework from the repository, but, you will need to remove it from your history. To do so, do these following steps in your favorite terminal:

* Return to the commit before adding the framework named **"Comment Mapping to static category"**

`git reset e40c91fb9de2fba63990e741ac85f4e883e44661 --hard`

* Push your changes, forcing the history change and erasing the latest commits

`git push -f origin mapbox-ios-3.5.0`

README!!: Make sure you are in the correct commit before running this command, after this, there is no turn back.

We ask you to do this because we have strictly prohibit to do `git push -f` in Xamarin/Microsoft repos.

Thank's for your help and for your comprehension.

If you have any doubt, don't hesitate to ask.

2017-05-19 10:48 UTC, davideme commented
@SotoiGhost Sorry for pushing the framework on this branch, It was needed for the project that I'm working on.
I wrapped the missing method that used IntPtr.

2017-06-05 14:07 UTC, davideme commented
@SotoiGhost please can you review and update the PR ?
All the changes requested are committed and pushed since 2 weeks ago, it's now become a blocker for the project I'm working on.

2017-06-09 14:59 UTC, merged