Moving RadialProgress to the public repo
xamarin/XamarinComponents pull request #149
Opened 2017-04-24 20:46 UTC by bholmes

2017-04-24 20:59 UTC, mattleibow requested changes
Looks pretty good, except for a few small tweaks needed:
 - copyright text and dates
 - in some files there is a mix between tabs and space (better to fix them now)

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/component/Manifest.xml
> +<addon format="1">
should this file be here?

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/nuget/Xamarin.RadialProgress.nuspec
> +    <copyright>Copyright 2016 Xamarin</copyright>
is this correct? I have been using "Copyright © Xamarin. All Rights Reserved." which I think I copied from MapBox

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/nuget/Xamarin.RadialProgress.nuspec
> +    <owners>Xamarin Inc.</owners>
What should the `<authors>` and `<owners>` be for legal or whatnot.. I have just copied mapbox's "Xamarin"

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/samples/RadialProgress.Android.Sample/MainActivity.cs
> +            bigRadialProgress.LabelTextDelegate = (val) => Math.Floor(100-val).ToString().PadLeft(2, '0');
whitespace ;)

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/samples/RadialProgress.Android.Sample/RadialProgress.Android.Sample.csproj
> +    <AndroidSupportedAbis>armeabi;armeabi-v7a;x86</AndroidSupportedAbis>
are these the abis that we want?

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/samples/RadialProgress.iOS.Sample/SampleViewController.cs
> +            bigRadialProgressView.LabelTextDelegate = (val) => Math.Floor(100-val*100).ToString().PadLeft(2, '0');
whitespace

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/samples/RadialProgress.iOS.Sample/SampleViewController.cs
> +            tinyRadialProgressView = new RadialProgressView (progressType: RadialProgressViewStyle.Tiny);
whitespace

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/source/RadialProgress.Android/RadialProgressView.cs
> +        public RadialProgressView (Context context, IAttributeSet attributes) : base(context, attributes)
whitespace

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/source/RadialProgress.Android/RadialProgressView.cs
> +        public RadialProgressView (Context context, float minValue = 0f, float maxValue = 1f, RadialProgressViewStyle progressType = RadialProgressViewStyle.Big, Func<float, string> labelTextFunc = n
whitespace

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/source/RadialProgress.iOS/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.1.0")]
these version numbers should be "1.0.0.0"

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/source/RadialProgress.iOS/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright © Xamarin Inc. 2013")]
this may need updating

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/source/RadialProgress.iOS/RadialProgressView.cs
> +        public Func<nfloat, string> LabelTextDelegate { get; set; }
whitespaces

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/source/RadialProgress.iOS/RadialProgressView.cs
> +            LabelTextDelegate = labelText;
whitespace

2017-04-24 20:59 UTC, mattleibow commented on XPlat/RadialProgress/source/RadialProgress.iOS/RadialProgressView.cs
> +                percentageLabel.Text = (LabelTextDelegate == null) ? Math.Floor (percentage).ToString ().PadLeft (2, '0') : LabelTextDelegate(currentValue);
whitespace

2017-04-25 14:16 UTC, bholmes commented on XPlat/RadialProgress/nuget/Xamarin.RadialProgress.nuspec
> +    <owners>Xamarin Inc.</owners>
Either MSFT or Xamarin is fine in this case.  Because this is not a change in features, just an oss release, I am deciding to keep Xamarin.

2017-04-25 14:17 UTC, bholmes commented on XPlat/RadialProgress/nuget/Xamarin.RadialProgress.nuspec
> +    <copyright>Copyright 2016 Xamarin</copyright>
I have asked, and I have not been given good answers.  It is my understanding that it is not wrong.  Leaving as Xamarin.

2017-04-25 14:23 UTC, bholmes commented on XPlat/RadialProgress/source/RadialProgress.iOS/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.1.0")]
maybe, but it is more important that they do not change.

2017-04-25 14:24 UTC, bholmes commented on XPlat/RadialProgress/source/RadialProgress.iOS/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright © Xamarin Inc. 2013")]
Not at this time

2017-04-25 18:19 UTC, mattleibow approved these changes

2017-04-25 18:20 UTC, merged