Updated to Firebase Job Dispatcher 0.7.0.0
xamarin/XamarinComponents pull request #177
Opened 2017-07-13 18:14 UTC by topgenorth

New version of the Firebase Job Dispatcher on Github, this is the updated binding.

2017-07-13 18:14 UTC, dnfclas commented
@topgenorth,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-07-21 16:42 UTC, bholmes requested changes
One change needed otherwise I think this is good to merge.

2017-07-21 16:42 UTC, bholmes commented on Android/FirebaseJobDispatcher/source/Firebase.JobDispatcher/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.7.0.0")]
We do not  rev AssemblyVersion.  For bindings, the assembly version is usually just 1.0.0.0, and then we set the file version to the library version.  I suggest picking a version number and sticking with it. AssemblyFileVersion you can change.

2017-07-21 19:28 UTC, topgenorth commented
Changed the AssemblyVersion.

2017-07-21 19:36 UTC, merged