[UniversalImageLoader] Added .nuspec
xamarin/XamarinComponents pull request #186
Opened 2017-07-25 05:44 UTC by mattleibow

Blocked by: https://bugzilla.xamarin.com/show_bug.cgi?id=56436
Build log: https://gist.github.com/mattleibow/9f4fa0850fb920ca4b48e74a5a32c73b

> For type Java.Util.IQueue, base interface Java.Util.ICollection does not exist.

    BINDINGSGENERATOR : warning BG8C00: For type Java.Util.IQueue, base interface Java.Util.ICollection does not exist.
    BINDINGSGENERATOR : warning BG8502: Invalidating Java.Util.IQueue and all nested types because some of its interfaces were invalid.
    BINDINGSGENERATOR : warning BG8C00: For type UniversalImageLoader.Core.Assist.Deque.IDeque, base interface java.util.Queue<E> is invalid.
    BINDINGSGENERATOR : warning BG8502: Invalidating UniversalImageLoader.Core.Assist.Deque.IDeque and all nested types because some of its interfaces were invalid.
    BINDINGSGENERATOR : warning BG8C00: For type UniversalImageLoader.Core.Assist.Deque.IBlockingDeque, base interface com.nostra13.universalimageloader.core.assist.deque.Deque<E> is invalid.
    BINDINGSGENERATOR : warning BG8C00: For type Java.Util.Concurrent.IBlockingQueue, base interface Java.Util.IQueue is invalid.
    BINDINGSGENERATOR : warning BG8C00: For type Java.Util.Concurrent.IBlockingQueue, base interface Java.Util.ICollection does not exist.
    BINDINGSGENERATOR : warning BG8502: Invalidating Java.Util.Concurrent.IBlockingQueue and all nested types because some of its interfaces were invalid.
    BINDINGSGENERATOR : warning BG8C00: For type UniversalImageLoader.Core.Assist.Deque.IBlockingDeque, base interface java.util.concurrent.BlockingQueue<E> is invalid.
    BINDINGSGENERATOR : warning BG8502: Invalidating UniversalImageLoader.Core.Assist.Deque.IBlockingDeque and all nested types because some of its interfaces were invalid.
    BINDINGSGENERATOR : warning BG8C00: For type Java.Util.AbstractCollection, base interface Java.Util.ICollection does not exist.
    BINDINGSGENERATOR : warning BG8C00: For type Java.Util.AbstractQueue, base interface Java.Util.IQueue is invalid.
    BINDINGSGENERATOR : warning BG8C00: For type Java.Util.AbstractQueue, base interface Java.Util.ICollection does not exist.
    BINDINGSGENERATOR : warning BG8C00: For type UniversalImageLoader.Core.Assist.Deque.LinkedBlockingDeque, base interface com.nostra13.universalimageloader.core.assist.deque.BlockingDeque<E> is invalid.
    BINDINGSGENERATOR : warning BG8C00: For type UniversalImageLoader.Core.Assist.Deque.LinkedBlockingDeque, base interface com.nostra13.universalimageloader.core.assist.deque.BlockingDeque<E> is invalid.

2017-12-05 22:52 UTC, mattleibow commented
The issue has been resolved and can now be merged.

2018-05-02 20:39 UTC, newky2k requested changes

2018-05-02 20:39 UTC, newky2k commented on Android/UniversalImageLoader/component/component.yaml
>  publisher-url: http://xamarin.com/
Needs to be an FwLink

2018-05-02 20:39 UTC, newky2k commented on Android/UniversalImageLoader/component/component.yaml
>  src-url: https://github.com/xamarin/XamarinComponents/tree/master/Android/UniversalImageLoader
Needs to be an FwLink

2018-05-09 20:47 UTC, newky2k approved these changes

2018-05-09 20:56 UTC, merged