[SimplePing] Added the v1.4 component
xamarin/XamarinComponents pull request #206
Opened 2017-08-14 20:10 UTC by mattleibow

2017-08-16 19:27 UTC, bholmes requested changes
I need the external files to finish the review.

2017-08-16 19:27 UTC, bholmes commented on manifest.yaml
> +  MacBuildTargets: [ component, samples ]
Should we reverse the target order to match the others?

` MacBuildTargets: [ samples, component ]`

2017-08-16 19:27 UTC, bholmes commented on iOS/SimplePing/build.cake
> +Task ("externals")
externals folder is missing.  Can you please add it?

2017-08-16 19:27 UTC, bholmes commented on iOS/SimplePing/source/Xamarin.SimplePing/ApiDefinition.cs
> +		void DidStartWithAddress(SimplePing pinger, NSData address);
Should this be DidStart?  (suggestion)

2017-08-16 19:27 UTC, bholmes commented on iOS/SimplePing/source/Xamarin.SimplePing/ApiDefinition.cs
> +		void DidFailWithError(SimplePing pinger, NSError error);
Should this be DidFail? (suggestion)

2017-08-16 19:27 UTC, bholmes commented on iOS/SimplePing/source/Xamarin.SimplePing/ApiDefinition.cs
> +		void DidStartWithAddress(SimplePing pinger, NSData address);
If changed, review your documentation.

2017-08-16 19:27 UTC, bholmes commented on iOS/SimplePing/source/Xamarin.SimplePing/ApiDefinition.cs
> +		void DidFailWithError(SimplePing pinger, NSError error);
If changed, review your documentation.

2017-08-17 12:41 UTC, mattleibow commented on manifest.yaml
> +  MacBuildTargets: [ component, samples ]
changed

2017-08-17 12:42 UTC, mattleibow commented on iOS/SimplePing/build.cake
> +Task ("externals")
done.

2017-08-17 12:47 UTC, mattleibow commented on iOS/SimplePing/source/Xamarin.SimplePing/ApiDefinition.cs
> +		void DidFailWithError(SimplePing pinger, NSError error);
changed.

2017-08-17 12:47 UTC, mattleibow commented on iOS/SimplePing/source/Xamarin.SimplePing/ApiDefinition.cs
> +		void DidStartWithAddress(SimplePing pinger, NSData address);
changed.

2017-08-18 22:03 UTC, bholmes approved these changes

2017-08-18 22:03 UTC, merged

2017-08-22 19:26 UTC, jamesmontemagno commented
Is this puppy going up on NuGet?

2017-08-29 14:32 UTC, mattleibow commented
@jamesmontemagno Yes. We are waiting on a review.

2017-08-29 20:41 UTC, bholmes commented
https://www.nuget.org/packages/Xamarin.SimplePing/