Update BetterPickers to NuGet
xamarin/XamarinComponents pull request #255
Opened 2017-11-20 17:18 UTC by mattleibow

Added NuGet, licensing and improved the project files.

2017-11-20 17:48 UTC, bholmes requested changes

2017-11-20 17:48 UTC, bholmes commented on Android/BetterPickers/External-Dependency-Info.txt
> +Licensed under the Apache License, Version 2.0 (the "License");
replace this text with the contents of this file...  

https://github.com/BoD/android-switch-backport/blob/master/NOTICE.txt

2017-11-20 17:48 UTC, bholmes commented on Android/BetterPickers/External-Dependency-Info.txt
> +
You need to add the following...  

 - Copyright (C) 2013 The Android Open Source Project
 - Copyright (C) 2012 Google Inc.
 - Copyright (C) 2012 Jake Wharton
 - Copyright (C) 2011 Patrik Akerfeldt

2017-11-28 21:14 UTC, bholmes approved these changes

2017-11-28 21:14 UTC, merged

2017-11-30 07:29 UTC, mattleibow commented
@bholmes Thanks for the fixes.