[SWTableViewCell] to Nuget.
xamarin/XamarinComponents pull request #315
Opened 2018-02-20 10:45 UTC by adlair

2018-02-20 18:38 UTC, bholmes commented on iOS/SWTableViewCell/component/component.yaml
> +version: 0.3.7
Bump this to 0.3.7.1

2018-02-20 18:58 UTC, SotoiGhost commented on iOS/SWTableViewCell/build.cake
> +	"platform :ios, '11.2'",
Does this pod support only the most recent iOS version?

2018-02-22 17:57 UTC, newky2k requested changes
You should also specify nobuild: true on the sample and no_build to stoe the source being built in the component.yaml

Also does this need a external dependencies file for the cocoapod

2018-02-22 17:57 UTC, newky2k commented on iOS/SWTableViewCell/nuget/Xamarin.SWTableViewCell.nuspec
> +    <projectUrl>https://components.xamarin.com/view/swtableviewcell</projectUrl>
Needs to be an FWLink

2018-02-22 17:57 UTC, newky2k commented on iOS/SWTableViewCell/nuget/Xamarin.SWTableViewCell.nuspec
> +    <licenseUrl>https://components.xamarin.com/license/swtableviewcell</licenseUrl>
Needs to be an FWLink

2018-03-13 21:23 UTC, newky2k requested changes

2018-03-13 21:23 UTC, newky2k commented on iOS/SWTableViewCell/component/component.yaml
> +    installNuGets:
Missing remove part of the nuget installation.  should remove the source project

2018-03-13 21:23 UTC, newky2k commented on iOS/SWTableViewCell/component/component.yaml
need to add the local-nuget-repo: ../output and is_shell: true

2018-03-13 21:31 UTC, newky2k commented on iOS/SWTableViewCell/component/component.yaml
no externals file in the component.yaml

2018-03-13 21:35 UTC, newky2k commented
It fails to build the component becuase it cannot install the nuget into the sample, becuase the local-nuget-repo is not provided

2018-03-21 20:45 UTC, newky2k requested changes

2018-03-21 20:45 UTC, newky2k commented on iOS/SWTableViewCell/component/component.yaml
> +    path: ../samples/SWTableViewCellSample.
missing the file extensions on the sample solution

2018-03-21 21:03 UTC, newky2k requested changes

2018-03-21 21:03 UTC, newky2k commented on iOS/SWTableViewCell/component/component.yaml
> +license: ../License.md
License.md is not in the root folder so the component will not compile

2018-03-27 20:37 UTC, newky2k approved these changes

2018-03-28 16:30 UTC, newky2k requested changes

2018-03-28 16:30 UTC, newky2k commented on iOS/SWTableViewCell/samples/SWTableViewCellSample/.vs/SWTableViewCellSample/xs/UserPrefs.xml
> +﻿<Properties StartupConfiguration="{424FB004-7068-44D5-880E-CB76B7B8A653}|Default">
This file needs to be removed, as well as the .vs folder in general

2018-04-16 17:50 UTC, newky2k approved these changes

2018-04-18 10:39 UTC, merged