[JASidePanels] to Nuget.
xamarin/XamarinComponents pull request #317
Opened 2018-02-20 12:42 UTC by adlair

2018-02-20 18:24 UTC, bholmes requested changes
There is probably more to do.  This is my feedback for now.

2018-02-20 18:24 UTC, bholmes commented on iOS/SidePanels/build.cake
> +var IOS_PODS = new List<string> {
This library is not a binding project.  It is a port of the library JASidePanels.  You do not need to fetch the native libraries.

2018-02-20 18:24 UTC, bholmes commented on iOS/SidePanels/build.cake
> +Task ("externals").IsDependentOn ("externals-base").Does (() =>
This too can be removed because you do not need the native library.

2018-02-20 18:24 UTC, bholmes commented on iOS/SidePanels/component/component.yaml
> +version: 1.3.2
The version should be 2.0.0.3

2018-02-20 18:24 UTC, bholmes commented on iOS/SidePanels/nuget/Xamarin.SidePanels.nuspec
> +    <version>1.3</version>
I think this version should be  2.0.0.3 too.

2018-02-20 18:24 UTC, bholmes commented on iOS/SidePanels/nuget/Xamarin.SidePanels.nuspec
> +    <projectUrl>https://components.xamarin.com/view/jasidepanels</projectUrl>
These 2 links need to be fwlinks and point back to GitHub

2018-02-20 18:24 UTC, bholmes commented on iOS/SidePanels/component/component.yaml
>  publisher: Xamarin Inc
Move the License.md file to the root of the project.

2018-02-20 18:55 UTC, SotoiGhost requested changes

2018-02-20 18:55 UTC, SotoiGhost commented on iOS/SidePanels/build.cake
> +	"platform :ios, '11.2'",
Does this pod support only the most recent iOS version?

2018-02-22 19:11 UTC, newky2k requested changes
You need to set all of the samples in the component.yaml file to nobuild as they do not need to be built as part of the build process.

2018-02-22 19:11 UTC, newky2k commented on iOS/SidePanels/nuget/Xamarin.SidePanels.nuspec
> +    <file src="output/unified/SidePanels.dll" target="lib/Xamarin.iOS" />
Need to include an external dependencies file

2018-03-14 21:12 UTC, newky2k requested changes

2018-03-14 21:12 UTC, newky2k commented on iOS/SidePanels/component/component.yaml
> +    installNuGets:
remove is missing from the installNugets bit

2018-03-14 21:12 UTC, newky2k commented on iOS/SidePanels/component/component.yaml
> +    installNuGets:
remove is missing from the installNugets bit

2018-03-14 21:12 UTC, newky2k commented on iOS/SidePanels/component/component.yaml
> +    installNuGets:
remove is missing from the installNugets bit

2018-03-14 21:12 UTC, newky2k commented on iOS/SidePanels/component/component.yaml
>  monodoc: ../docs/
missing the local-nuget-repo tag

2018-03-14 21:12 UTC, newky2k commented on iOS/SidePanels/component/component.yaml
>  monodoc: ../docs/
Also missing the external dependencies file being added to the xam file

2018-03-14 21:12 UTC, newky2k commented on iOS/SidePanels/component/component.yaml
>  monodoc: ../docs/
is_Shell is missing

2018-03-14 21:21 UTC, newky2k commented
Fails to compile component with the following message -> https://gist.github.com/newky2k/bcb97aceb1d85867a93557744492ec38

2018-03-22 21:39 UTC, newky2k requested changes

2018-03-22 21:39 UTC, newky2k commented on iOS/SidePanels/build.cake
> +RunTarget (TARGET);
The build.cake file has no nuget section so the nuget is not getting built and the component will not compile as its referencing it.

2018-04-18 20:35 UTC, newky2k requested changes
All of the samples need to be updated to support iPhone X.  This is simply a matter of adding a LaunchScreen file and setting it in the Info.Plist.  It will then do fullscreen on iPhone X

2018-04-20 06:18 UTC, adlair commented
@newky2k I added iPhone X support on https://github.com/xamarin/XamarinComponents/pull/357. I had many problems with my local repo. :(

2018-04-26 19:29 UTC, bholmes commented
There was a problem with Git and GitHub where the PR was disconnected from the fork.  This PR is patched and opened again in #357.

2018-04-26 19:29 UTC, closed without merging