[StickyListHeaders] to Nuget.
xamarin/XamarinComponents pull request #344
Opened 2018-04-07 07:13 UTC by adlair

2018-04-16 20:42 UTC, newky2k commented on Android/StickyListHeaders/component/component.yaml
> +          - Xamarin.StickyListHeaders
The sample is not adding the library from the nuget package

2018-04-17 18:49 UTC, newky2k requested changes

2018-04-17 18:49 UTC, newky2k commented on Android/StickyListHeaders/nuget/Xamarin.StickyListHeaders.nuspec
> +    <file src="output/StickyListHeaders.dll" target="lib/Xamarin.Android" />
This is the wrong target name - to should be MonoAndroid60 or MonoAndroid80, what ever the minimum version of android is

2018-04-24 00:52 UTC, adlair commented
I added new changes in the nest PR: https://github.com/xamarin/XamarinComponents/pull/362.

2018-04-26 19:29 UTC, bholmes commented
There was a problem with Git and GitHub where the PR was disconnected from the fork.  This PR is patched and opened again in #362.

2018-04-26 19:29 UTC, closed without merging