[JazzyViewPager] to Nuget.
xamarin/XamarinComponents pull request #347
Opened 2018-04-10 05:17 UTC by adlair

2018-04-17 18:49 UTC, newky2k requested changes

2018-04-17 18:49 UTC, newky2k commented on Android/JazzyViewPager/nuget/Xamarin.JazzyViewPager.nuspec
> +    <file src="output/JazzyViewPager.dll" target="lib/Xamarin.Android" />
This is the wrong target name - to should be MonoAndroid60 or MonoAndroid80, what ever the minimum version of android is

2018-04-24 00:51 UTC, adlair commented
I added new changes in the next PR: https://github.com/xamarin/XamarinComponents/pull/363.

2018-04-26 19:30 UTC, bholmes commented
There was a problem with Git and GitHub where the PR was disconnected from the fork.  This PR is patched and opened again in #363.

2018-04-26 19:30 UTC, closed without merging