[JazzyViewPager] Nuspec file updated.
xamarin/XamarinComponents pull request #363
Opened 2018-04-24 00:50 UTC by adlair

2018-05-01 08:36 UTC, jzeferino approved these changes
LGTM.

2018-05-01 20:46 UTC, newky2k requested changes

2018-05-01 20:46 UTC, newky2k commented on Android/JazzyViewPager/nuget/Xamarin.JazzyViewPager.nuspec
> +    <file src="output/JazzyViewPager.dll" target="lib/Xamarin.Android" />
This is the wrong target name - to should be MonoAndroid60 or MonoAndroid80, what ever the minimum version of android is

2018-05-23 20:29 UTC, newky2k approved these changes

2018-05-23 20:29 UTC, merged