[libphonenumber] initial commit of Google's libphonenumber
xamarin/XamarinComponents pull request #375
Opened 2018-05-07 18:55 UTC by Redth

2018-05-07 19:04 UTC, mattleibow submitted a review, later dismissed

2018-05-07 19:04 UTC, mattleibow commented on Android/Google.LibPhoneNumber/External-Dependency-Info.txt
> +Xamarin Components for Google's Android Things Support Library incorporates
This is the wrong library name.

2018-05-07 19:04 UTC, mattleibow commented on Android/Google.LibPhoneNumber/nuget/Xamarin.Google.LibPhoneNumber.nuspec
> +    <licenseUrl></licenseUrl>
These two things may or may not be correct.

2018-05-07 19:05 UTC, mattleibow commented
I like the new SDK-style projects ❤️

2018-06-08 15:57 UTC, newky2k requested changes

2018-06-08 15:57 UTC, newky2k commented on Android/Google.LibPhoneNumber/build.cake
> +			SolutionPath = "./Google.LibPhoneNumber.sln",
This is the wrong name for the solution file

2018-06-08 15:57 UTC, newky2k commented on Android/Google.LibPhoneNumber/build.cake
> +					FromFile = "./source/bin/Release/Xamarin.Google.LibPhoneNumber.dll",
The output goes into a monodroid sub folder, not this location

2018-06-08 16:10 UTC, newky2k approved these changes

2018-06-08 17:43 UTC, merged