[Explosions] to Nuget.
xamarin/XamarinComponents pull request #401
Opened 2018-06-05 20:26 UTC by adlair

2018-07-17 20:23 UTC, newky2k requested changes

2018-07-17 20:23 UTC, newky2k commented on Android/Explosions/component/component.yaml
> +  ios-unified: Xamarin.Explosions, Version=1.0.0.2
Wrong target as this is an android project

2018-07-17 20:23 UTC, newky2k commented on Android/Explosions/nuget/Xamarin.Explosions.nuspec
> +    <file src="output/Explosions.dll" target="lib/Xamarin.MonoAndroid8123" />
Incorrect target, this should be MonoAndroid23

2018-07-20 03:11 UTC, adlair commented
Issues fixed.

2018-07-23 17:52 UTC, newky2k approved these changes

2018-07-23 17:52 UTC, merged