[SDWebImage] Updated to v4.4
xamarin/XamarinComponents pull request #415
Opened 2018-07-06 11:48 UTC by adlair

2018-07-10 17:23 UTC, bholmes commented
There appears to be a merge issue that was committed.  I doubt the library will build.  @adlair needs to get this PR building again.

2018-07-17 17:43 UTC, bholmes submitted a review, later dismissed

2018-07-17 17:43 UTC, bholmes commented on iOS/SDWebImage/component/component.yaml
> +=======
This is a mistake that needs fixed

2018-07-17 17:43 UTC, bholmes commented on iOS/SDWebImage/samples/SDWebImageSimpleSample/SDWebImageSimpleSample/Info.plist
> +<<<<<<< HEAD
This is a mistake that needs fixed

2018-07-17 17:43 UTC, bholmes commented on iOS/SDWebImage/component/component.yaml
> +<<<<<<< HEAD
This is a mistake that needs fixed

2018-07-17 17:43 UTC, bholmes commented on iOS/SDWebImage/nuget/SDWebImage.nuspec
> +<<<<<<< HEAD
This is a mistake that needs fixed

2018-07-17 17:43 UTC, bholmes commented on iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/Info.plist
> +<<<<<<< HEAD
This is a mistake that needs fixed

2018-07-17 17:43 UTC, bholmes commented on iOS/SDWebImage/License.md~6b6330588e1d0c93dea410c83be94292d3f4402b
> +**The MIT License (MIT)**
This file is added by mistake

2018-07-17 17:43 UTC, bholmes commented on iOS/SDWebImage/License.md~HEAD
> +**The MIT License (MIT)**
This file is added by mistake

2018-07-18 17:37 UTC, adlair commented
Issues fixed.

2018-07-23 20:22 UTC, newky2k requested changes
when running  ->

sh ../../build.sh -t=samples

get this error



"/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample.sln" (Build target) (1) ->
"/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj" (default target) (2) ->
(_CoreCompileInterfaceDefinitions target) -> 
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018: The "IBTool" task failed unexpectedly. [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018: System.ArgumentException: An item with the same key has already been added. Key: CFBundleName [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException (System.Object key) [0x00006] in <bb7b695b8c6246b3ac1646577aea7650>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000ad] in <bb7b695b8c6246b3ac1646577aea7650>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <bb7b695b8c6246b3ac1646577aea7650>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at Xamarin.MacDev.PDictionary.Add (System.String key, Xamarin.MacDev.PObject value) [0x00001] in <61a9397755bb4851982b9c1872ed8a1e>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at Xamarin.MacDev.PropertyListFormat+XmlFormat+Context.ReadDict (Xamarin.MacDev.PDictionary dict) [0x000dc] in <61a9397755bb4851982b9c1872ed8a1e>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at Xamarin.MacDev.PropertyListFormat+ReadWriteContext.ReadObject () [0x000ed] in <61a9397755bb4851982b9c1872ed8a1e>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at Xamarin.MacDev.PObject.FromFile (System.String fileName, System.Boolean& isBinary) [0x00042] in <61a9397755bb4851982b9c1872ed8a1e>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at Xamarin.MacDev.PDictionary.FromFile (System.String fileName, System.Boolean& isBinary) [0x00001] in <61a9397755bb4851982b9c1872ed8a1e>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at Xamarin.MacDev.PDictionary.FromFile (System.String fileName) [0x00001] in <61a9397755bb4851982b9c1872ed8a1e>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at Xamarin.MacDev.Tasks.IBToolTaskBase.Execute () [0x000b6] in <61a9397755bb4851982b9c1872ed8a1e>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in <61115f75067146fab35b10183e6ee379>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1324,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x00212] in <61115f75067146fab35b10183e6ee379>:0  [/Users/davidhumphreys/Git/XamarinComponents/iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj]

2018-07-23 20:27 UTC, newky2k requested changes

2018-07-23 20:27 UTC, newky2k commented on iOS/SDWebImage/nuget/SDWebImage.nuspec
> +    <version>4.0.0-beta2</version>
should this be 4.4?

2018-07-23 20:27 UTC, newky2k commented on iOS/SDWebImage/component/component.yaml
> +version: 4.0.0
4.4.0

2018-07-27 02:11 UTC, adlair commented on iOS/SDWebImage/component/component.yaml
> +version: 4.0.0
Fixed.

2018-07-30 16:23 UTC, newky2k requested changes

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Should be Automatic developer

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Should Automatic developer

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Should an Automatic developer

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Should an Automatic developer

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageSampleMac/SDWebImageSampleMac/SDWebImageSampleMac.csproj
> +    <CodeSigningKey>Mac Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodeSigningKey>
Should an Automatic developer

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageSampleMac/SDWebImageSampleMac/SDWebImageSampleMac.csproj
> +    <CodeSigningKey>Mac Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodeSigningKey>
Should an Automatic developer

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageSampleTV/SDWebImageSampleTV/SDWebImageSampleTV.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Should an Automatic developer

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageSampleTV/SDWebImageSampleTV/SDWebImageSampleTV.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Should an Automatic developer

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageSampleTV/SDWebImageSampleTV/SDWebImageSampleTV.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Should an Automatic developer

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageSampleTV/SDWebImageSampleTV/SDWebImageSampleTV.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Should an Automatic developer

2018-07-30 16:23 UTC, newky2k commented on iOS/SDWebImage/samples/SDWebImageSimpleSample/SDWebImageSimpleSample/SDWebImageSimpleSample.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Should an Automatic developer

2018-07-30 16:24 UTC, newky2k requested changes

2018-07-30 16:24 UTC, newky2k commented on iOS/SDWebImage/nuget/SDWebImage.nuspec
>      <file src="output/unified/SDWebImage.dll" target="lib/Xamarin.iOS" />
<file src="output/unified/SDWebImage.dll" target="lib/Xamarin.iOS" />

is line is no longer needed and doesn't work

2018-08-02 17:27 UTC, newky2k requested changes
Need to make sure that the siging cert is set to automatic on all build configurations on all samples

2018-08-03 17:11 UTC, Redth commented on iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Needs fixing

2018-08-03 17:11 UTC, Redth commented on iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Needs fixing

2018-08-03 17:11 UTC, Redth commented on iOS/SDWebImage/samples/SDWebImageMapKitSample/SDWebImageMapKitSample/SDWebImageMapKitSample.csproj
> +    <CodesignKey>iPhone Developer: Jesus Adlair Cerecedo Mendez (83Q48VP5BY)</CodesignKey>
Needs fixing, check everywhere for this please.

2018-08-14 04:54 UTC, adlair commented
Bundle signing fixed.

2018-08-14 17:41 UTC, newky2k approved these changes

2018-08-14 17:41 UTC, merged