Google GRPC initial commit (Core, Stub, OkHttp, Protobuf.Lite)
xamarin/XamarinComponents pull request #435
Opened 2018-08-07 09:02 UTC by moljac

2018-08-09 17:57 UTC, newky2k requested changes
Found some issues with the package meta data, needs to be fixed in all of the packages, but nuget target fails as the path to the csproj is incorrect

2018-08-09 17:57 UTC, newky2k commented on XPlat/Google.Grpc/build.cake
> +				"./source/Xamarin.Protobuf.Lite.Bindings.XamarinAndroid/Xamarin.Protobuf.Lite.Bindings.XamarinAndroid.csproj",
This path is not the correct path for the project

./source/Xamarin.Grpc.Protobuf.Lite.Bindings.XamarinAndroid/Xamarin.Grpc.Protobuf.Lite.Bindings.XamarinAndroid.csproj

2018-08-09 17:57 UTC, newky2k commented on XPlat/Google.Grpc/source/Xamarin.Grpc.Core.Bindings.XamarinAndroid/Xamarin.Grpc.Core.Bindings.XamarinAndroid.csproj
> +        <Copyright>Copyright 2018</Copyright>
Copyright is incorrect

2018-08-09 17:57 UTC, newky2k commented on XPlat/Google.Grpc/source/Xamarin.Grpc.Core.Bindings.XamarinAndroid/Xamarin.Grpc.Core.Bindings.XamarinAndroid.csproj
> +        https://github.com/grpc/grpc
links should be fwlinks

2018-08-09 17:57 UTC, newky2k commented on XPlat/Google.Grpc/source/Xamarin.Grpc.Core.Bindings.XamarinAndroid/Xamarin.Grpc.Core.Bindings.XamarinAndroid.csproj
> +        https://github.com/grpc/grpc
links should be fwlinks

2018-08-09 17:57 UTC, newky2k commented on XPlat/Google.Grpc/source/Xamarin.Grpc.Core.Bindings.XamarinAndroid/Xamarin.Grpc.Core.Bindings.XamarinAndroid.csproj
> +        https://github.com/grpc/grpc/blob/master/LICENSE
links should be fwlinks

2018-08-09 17:57 UTC, newky2k commented on XPlat/Google.Grpc/source/Xamarin.Grpc.Core.Bindings.XamarinAndroid/Xamarin.Grpc.Core.Bindings.XamarinAndroid.csproj
> +        <Owners>Microsoft Corporation</Owners>
Should just be microsoft

2018-08-09 17:57 UTC, newky2k commented on XPlat/Google.Grpc/source/Xamarin.Grpc.Core.Bindings.XamarinAndroid/Xamarin.Grpc.Core.Bindings.XamarinAndroid.csproj
> +        <Authors>Microsoft / Xamarin</Authors>
should just be microsoft

2018-08-13 20:16 UTC, moljac commented
review remarks fixes done!

2018-08-16 18:26 UTC, newky2k approved these changes

2018-08-16 18:28 UTC, merged