First Implementation of Google Dagger for Android
xamarin/XamarinComponents pull request #694
Opened 2019-10-06 23:52 UTC by GuillaumeSE

Google Dagger is required for Firebase InAppMessaging in Xamarin GooglePlayServiceComponent Rep.

2019-10-06 23:52 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/xamarin/XamarinComponents?pullRequest=694) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/XamarinComponents?pullRequest=694) before we can accept your contribution.<br/><br/>:x: GuillaumeSE [sign now](https://cla.dotnetfoundation.org/xamarin/XamarinComponents?pullRequest=694)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/XamarinComponents?pullRequest=694) it.</sub>

2019-10-07 15:04 UTC, Redth requested changes
Thanks so much for this!  A few minor changes requested, but awesome work on it, and much appreciated!

2019-10-07 15:04 UTC, Redth commented on Android/GoogleDagger/source/Dagger/Transforms/Metadata.xml
> +	<attr path="/api/package[@name='com.google.dagger.dagger']" name="managedName">Google.Dagger.Dagger</attr>
I think maybe we should be ok with just `Google.Dagger` as the namespace.

2019-10-07 15:04 UTC, Redth commented on Android/GoogleDagger/source/Dagger/Dagger.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Could you make this `<Project Sdk="MSBuild.Sdk.Extras/2.0.54">` to use the newer sdk extras package?  Also see some comments below to remove unnecessary bits after this change...

2019-10-07 15:04 UTC, Redth commented on Android/GoogleDagger/source/Dagger/Dagger.csproj
> +  <ItemGroup>
Remove this bit if we are using the Sdk specifier in the <Project element

2019-10-07 15:04 UTC, Redth commented on Android/GoogleDagger/source/Dagger/Dagger.csproj
> +  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />
Remove this bit as well if we are using Sdk specifier in the <Project element...

2019-10-07 15:04 UTC, Redth commented on Android/GoogleDagger/source/Dagger/Additions/AboutAdditions.txt
> +﻿Additions allow you to add arbitrary C# to the generated classes
Could you remove this file?

2019-10-07 15:04 UTC, Redth commented on Android/GoogleDagger/source/Dagger/Additions/Additions.cs
> +namespace Google.Dagger.Dagger {
Namespace change here, though in practice we could just remove this file altogether if it's not specifying anything

2019-10-07 15:04 UTC, Redth commented on Android/GoogleDagger/External-Dependency-Info.txt
> +# https://github.com/google/auto
URL I think should be: https://github.com/google/dagger

2019-10-07 16:02 UTC, moljac commented
Seems like nuget download of nuget validation cake script is failing

```
Downloading script from https://raw.githubusercontent.com/xamarin/XamarinComponents/GoogleDaggerAndroid/.ci/validation.cake...
Invoke-WebRequest : 404: Not Found
```

2019-10-07 16:32 UTC, Redth commented on Android/GoogleDagger/source/Dagger/Dagger.csproj
> +    <PackageProjectUrl>https://go.microsoft.com/fwlink/?linkid=2091414</PackageProjectUrl>
Can you leave these nodes both empty for now?  These links aren't correct but we will fill them out properly after :)

2019-10-07 18:10 UTC, merged

2019-10-07 18:10 UTC, Redth commented
Thank you!!